"""`mg target ...` — the growth engine commands."""
from __future__ import annotations

import json
import sys
from pathlib import Path

from . import model as m, store, growth as gr, governance as gov, ai, intake
from .cli import ok, warn, err, head, dim, c, C, _confirm


def _save(root: Path, t: gr.Target) -> None:
    store.save_target(root, t)
    store.write_target_artifact(root, t.slug, "TARGET.md", render_target(t))


def _next(t: gr.Target) -> str:
    if t.status == gr.IDENTIFIED:
        return f"mg target research {t.slug}   (then: mg target ingest {t.slug} target-research)"
    if t.status == gr.RESEARCHED:
        return f"mg target assess {t.slug}"
    if t.status == gr.PRIORITIZED:
        act = t.fit.recommended_action
        if act == "Initiate outreach":
            return f"mg target draft {t.slug}"
        if act in ("Monitor", "Wait for trigger"):
            return f"mg target monitor {t.slug} --reason '...'"
        if act == "Disqualify":
            return f"mg target disqualify {t.slug} --reason '...'"
        return f"mg target draft {t.slug}   (or monitor / disqualify)"
    if t.status == gr.CONTACTED:
        last = t.last_touch()
        if last and last.status == "draft":
            return f"mg target approve {t.slug}   (founder review before sending)"
        return f"mg target respond {t.slug} --kind positive|neutral|negative|none"
    if t.status == gr.ENGAGED:
        return f"mg target convert {t.slug}"
    if t.status == gr.MONITORING:
        return f"Monitoring. mg target assess {t.slug} when a trigger appears."
    if t.status == gr.CONVERTED:
        return f"Converted — continue in the sales pipeline: mg status {t.converted_to}"
    return "—"


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def render_target(t: gr.Target) -> str:
    def rows(items, fmt, empty="| — | *none* | — |"):
        return "\n".join(fmt(x) for x in items) or empty
    conf = rows(t.confirmed(), lambda e: f"| `{e.ref}` | {e.statement} | {e.source} |")
    inf = rows(t.inferences(), lambda e: f"| `{e.ref}` | {e.statement} | {e.source} |")
    unk = rows(t.unknowns(), lambda e: f"| `{e.ref}` | {e.statement} | — |")
    sig = rows(t.signals,
               lambda s: f"| {s.kind} | {s.signal} | `{s.evidence_ref or '—'}` |",
               "| — | *none matched* | — |")
    touches = rows(
        t.touches,
        lambda x: (f"| {x.seq} | {x.channel or '—'} | {x.purpose[:44] or '—'} | {x.status} | "
                   f"{x.sent_on or '—'} | {x.response_kind or '—'} |"),
        "| — | — | *no outreach* | — | — | — |")
    contacts = rows(t.contacts,
                    lambda x: f"| {x.name or '—'} | {x.role or '—'} | {x.email or '—'} |",
                    "| — | — | — |")
    return f"""<!-- Generated by tools/mg from target.json. Do not edit by hand.
     Procedure: the growth engine. Targets are pre-contact prospects and live
     here, not in clients/, until someone actually engages. -->
# TARGET — {t.company.name or t.slug}

**Status:** {t.status}
**Identified:** {t.identified_on} via {t.identified_via or '*not recorded*'}
**Campaign:** {t.campaign or '—'}
**Industry:** {t.company.industry or '—'} · **Size:** {t.company.approximate_size or '—'}
**Website:** {t.company.website or '—'}

---

## 1. Contacts

*Roles are recorded as published. D-021 sets the expected buyer roles; a role
is still never inferred from a name or a title pattern.*

| Name | Role | Email |
|---|---|---|
{contacts}

## 2. Confirmed Public Information

*Observed, with a source. These are the only statements an outreach message may
rest on.*

| Ref | Statement | Source |
|---|---|---|
{conf}

## 3. Reasoned Inference

*Not observed. **Never stated to a prospect as fact** (`BRAND.md` §6).*

| Ref | Inference | Basis |
|---|---|---|
{inf}

## 4. Unknown

*Recorded rather than filled in.*

| Ref | What is not known | |
|---|---|---|
{unk}

## 5. ICP Signals

*Quoted from `ICP.md`, each tied to the evidence supporting it.*

| Kind | Signal | Evidence |
|---|---|---|
{sig}

## 6. Fit

**Band:** {t.fit.band or '*not assessed*'} · **Recommended action:** {t.fit.recommended_action or '—'}
**Assessed:** {t.fit.assessed_on or '—'}

{t.fit.reasoning or '*No reasoning recorded.*'}

### Unknowns affecting the assessment
{chr(10).join('- ' + u for u in t.fit.unknowns) or '- *None recorded.*'}

## 7. Outreach

| # | Channel | Purpose | Status | Sent | Response |
|---|---|---|---|---|---|
{touches}

{('**Converted to:** `clients/' + t.converted_to + '` on ' + t.converted_on) if t.converted_to else ''}
"""


# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

def cmd_add(root, a):
    slug = a.slug or m.slugify(a.company)
    if store.target_exists(root, slug) and not a.force:
        err(f"Target {slug} already exists."); return 1
    dupes = store.find_target_duplicates(root, a.company, a.email or "", exclude=slug)
    dupes += [(s, w + " — already in the sales pipeline")
              for s, w in store.find_duplicates(root, a.company, a.email or "")]
    if dupes and not a.duplicate_ok:
        warn(f"{len(dupes)} existing record(s) look like this company:")
        for s2, why in dupes:
            print(f"    {c(s2, C.ACC)} — {why}")
        err("Refusing to create a duplicate. Pass --duplicate-ok if this is genuinely different.")
        return 1
    t = gr.Target(slug=slug, identified_on=m.today(),
                  identified_via=a.via or "", campaign=a.campaign or "")
    t.company.name = a.company
    t.company.website = a.website or ""
    t.company.industry = a.industry or ""
    t.company.approximate_size = a.size or ""
    t.company.location = a.location or ""
    if a.contact or a.email:
        t.contacts.append(m.Contact(name=a.contact or "", role=a.role or "",
                                    email=a.email or ""))
    t.log("identified", f"via {a.via or 'unrecorded'}", a.actor)
    _save(root, t)
    ok(f"Target {c(slug, C.ACC)} — {a.company}")
    if not a.via:
        warn("  No --via recorded. How targets are found is what tests the D-026 channel order.")
    print(f"\n{c('Next:', C.B)} {_next(t)}")
    return 0


def cmd_brief(root, a):
    t = store.load_target(root, a.slug)
    print(ai.target_packet(root, t, a.task))
    return 0


def cmd_ingest(root, a):
    t = store.load_target(root, a.slug)
    raw = Path(a.from_file).read_text(encoding="utf-8") if a.from_file else sys.stdin.read()
    try:
        data = ai.extract_json(raw)
    except Exception as e:
        err(f"Could not parse result: {e}"); return 1
    changed = ai.ingest_target(t, a.task, data, replace=a.replace)
    if not changed:
        warn("Nothing merged."); return 1
    if a.task == "target-research" and t.status == gr.IDENTIFIED and t.confirmed():
        t.set_status(gr.RESEARCHED, a.actor, "research recorded")
    if a.task == "target-assess" and t.fit.band and t.status in (gr.RESEARCHED, gr.IDENTIFIED):
        t.set_status(gr.PRIORITIZED, a.actor, f"assessed {t.fit.band}")
    t.log("ingest", f"{a.task}: {', '.join(changed)}"[:300], "ai")
    _save(root, t)
    ok(f"{a.slug} — merged {a.task}")
    for x in changed:
        print(f"    + {x}")
    if a.task == "target-research":
        if t.inferences():
            head("Inferences — never stated to the prospect as fact")
            for e in t.inferences():
                print(f"  {c(e.ref, C.WARN)} {e.statement}")
        if t.unknowns():
            head("Unknown — recorded, not filled in")
            for e in t.unknowns():
                print(f"  {c(e.ref, C.D)} {e.statement}")
    if a.task == "target-assess":
        dq = t.disqualifying()
        if dq:
            head("Disqualifying signals present")
            for s in dq:
                print(f"  {c(s.signal, C.ERR)}")
        dim("\n  Assessment recorded. The decision to contact remains the founder's.")
    if a.task == "target-message":
        problems = gr.grounding_problems(t, t.last_touch())
        if problems:
            head("Grounding problems — fix before approving")
            for p in problems:
                print(f"  {c('✗', C.ERR)} {p}")
    print(f"\n{c('Next:', C.B)} {_next(t)}")
    return 0


def cmd_draft(root, a):
    t = store.load_target(root, a.slug)
    missing = gr.readiness(t)
    if missing and not a.force:
        err("Not ready for outreach — missing:")
        for x in missing:
            print(f"    - {x}", file=sys.stderr)
        dim("  Contacting someone you have not researched is the outreach this "
            "company has decided not to do (`SALES.md` §8).")
        return 1
    if t.disqualifying() and not a.force:
        err("Disqualifying signal(s) present:")
        for s in t.disqualifying():
            print(f"    - {s.signal}", file=sys.stderr)
        return 1
    head(f"Draft outreach — {a.slug}")
    print(f"  Generate the draft:  {c('mg target brief ' + a.slug + ' target-message', C.ACC)}")
    print(f"  Then merge it:       mg target ingest {a.slug} target-message --from draft.json")
    dim("\n  Or record a message you wrote yourself:")
    dim(f"    mg target compose {a.slug} --purpose '...' --body-file msg.txt "
        f"--grounded-in E1 --grounded-in E2")
    return 0


def cmd_compose(root, a):
    """Record a human-written message, subject to the same grounding rule."""
    t = store.load_target(root, a.slug)
    body = Path(a.body_file).read_text(encoding="utf-8") if a.body_file else (a.body or "")
    if not body.strip():
        err("No message body. Pass --body or --body-file."); return 1
    touch = gr.Touch(seq=len(t.touches) + 1, channel=a.channel or "",
                     purpose=a.purpose or "", draft=body,
                     grounded_in=list(a.grounded_in or []),
                     status="draft", drafted_on=m.today())
    t.touches.append(touch)
    problems = gr.grounding_problems(t, touch)
    if problems and not a.force:
        err("Grounding problems:")
        for p in problems:
            print(f"    - {p}", file=sys.stderr)
        return 1
    money = gov.scan_for_open_values(root, body)
    if money:
        for x in money:
            err(x)
        return 1
    t.log("draft", f"touch #{touch.seq} composed", a.actor)
    _save(root, t)
    ok(f"{a.slug} — draft #{touch.seq} recorded")
    print(f"\n{c('Next:', C.B)} mg target approve {a.slug}")
    return 0


def cmd_approve(root, a):
    t = store.load_target(root, a.slug)
    touch = t.last_touch()
    if touch is None or touch.status != "draft":
        err("No draft awaiting approval."); return 1
    problems = gr.grounding_problems(t, touch)
    if problems and not a.force:
        err("Cannot approve — the draft is not grounded:")
        for p in problems:
            print(f"    - {p}", file=sys.stderr)
        return 1
    money = gov.scan_for_open_values(root, touch.draft)
    if money:
        for x in money:
            err(x)
        return 1
    head(f"Draft #{touch.seq} — {a.slug}")
    print(touch.draft)
    head("Rests on")
    for ref in touch.grounded_in:
        e = t.evidence(ref)
        print(f"  {ref}  {e.statement[:64] if e else '?'}  ({e.source if e else '—'})")
    if not a.approved_by:
        err("Outreach is client-facing communication and is founder-approved "
            "(`governance/AUTHORITY.md` §7). Re-run with --approved-by 'Founder'.")
        return 1
    if not _confirm("Approve this message for sending?", a.yes):
        err("Not approved."); return 1
    touch.status = "approved"
    touch.approved_by = a.approved_by
    touch.approved_on = m.today()
    touch.channel = a.channel or touch.channel
    t.log("approve", f"touch #{touch.seq} approved by {a.approved_by}", a.approved_by)
    _save(root, t)
    ok(f"Draft #{touch.seq} approved by {a.approved_by}")
    dim("  The tool does not send. Send it yourself, then record it:")
    print(f"\n{c('Next:', C.B)} mg target sent {a.slug} --channel <channel> --on <date>")
    return 0


def cmd_sent(root, a):
    t = store.load_target(root, a.slug)
    touch = t.last_touch()
    if touch is None or touch.status not in ("approved",):
        err("No approved draft to record as sent. Approve it first."); return 1
    touch.status = "sent"
    touch.sent_on = a.on or m.today()
    touch.channel = a.channel or touch.channel
    if not touch.channel:
        err("Record the channel it was sent through — channel evidence is what "
            "tests the D-026 channel priority order.")
        return 1
    if t.status in (gr.PRIORITIZED, gr.CONTACTED, gr.MONITORING, gr.NO_RESPONSE):
        t.set_status(gr.CONTACTED, a.actor, f"touch #{touch.seq} sent via {touch.channel}")
    t.log("sent", f"touch #{touch.seq} via {touch.channel}", a.actor)
    if a.follow_up:
        t.log("followup", f"follow-up due {a.follow_up}", a.actor)
    _save(root, t)
    ok(f"{a.slug} — touch #{touch.seq} sent via {touch.channel} on {touch.sent_on}")
    print(f"\n{c('Next:', C.B)} {_next(t)}")
    return 0


def cmd_respond(root, a):
    t = store.load_target(root, a.slug)
    sent = [x for x in t.touches if x.sent_on and not x.response_on]
    if not sent:
        err("No sent message awaiting a response."); return 1
    touch = sent[-1]
    touch.response_on = a.on or m.today()
    touch.response_kind = a.kind
    touch.response_text = a.text or ""
    touch.status = "responded" if a.kind != "none" else "no response"
    if a.kind == "positive":
        t.set_status(gr.ENGAGED, a.actor, "positive response")
    elif a.kind in ("neutral", "negative"):
        t.set_status(gr.MONITORING if a.kind == "neutral" else gr.DISQUALIFIED,
                     a.actor, f"{a.kind} response")
    else:
        t.set_status(gr.NO_RESPONSE, a.actor, "no response")
    t.log("response", f"touch #{touch.seq}: {a.kind}", a.actor)
    _save(root, t)
    ok(f"{a.slug} — {a.kind} response recorded · status {t.status}")
    print(f"\n{c('Next:', C.B)} {_next(t)}")
    return 0


def cmd_monitor(root, a):
    t = store.load_target(root, a.slug)
    if not a.reason:
        err("A monitored target needs a reason, or it is just a forgotten one."); return 1
    t.set_status(gr.MONITORING, a.actor, a.reason)
    t.log("monitor", a.reason + (f" (revisit {a.revisit})" if a.revisit else ""), a.actor)
    _save(root, t)
    ok(f"{a.slug} monitoring — {a.reason}")
    if not a.revisit:
        warn("  No --revisit date. It will not resurface on its own.")
    return 0


def cmd_disqualify(root, a):
    t = store.load_target(root, a.slug)
    if not a.reason:
        err("Disqualification reasoning is market-selection evidence under D-019 and D-036 "
            "(`ICP.md` §7). Record why.")
        return 1
    t.set_status(gr.DISQUALIFIED, a.actor, a.reason)
    t.log("disqualify", a.reason, a.actor)
    _save(root, t)
    ok(f"{a.slug} disqualified — {a.reason}")
    dim("  Record retained; the reasoning is ICP evidence.")
    return 0


def cmd_convert(root, a):
    """Target -> lead, carrying the research rather than retyping it."""
    t = store.load_target(root, a.slug)
    blockers = gr.conversion_blockers(t)
    if blockers and not a.force:
        err("Cannot convert to a lead:")
        for b in blockers:
            print(f"    - {b}", file=sys.stderr)
        return 1
    slug = a.to or t.slug
    if store.exists(root, slug) and not a.force:
        err(f"clients/{slug} already exists. Pass --to <slug> or --force."); return 1

    opp = m.Opportunity(slug=slug, created_on=m.today())
    opp.company = m.Company(**m.to_dict(t.company))
    opp.contacts = [m.from_dict(m.Contact, m.to_dict(x)) for x in t.contacts]
    opp.qualification.source = (t.identified_via or "outbound") + \
        (f" · campaign {t.campaign}" if t.campaign else "")
    pos = t.positive_response()
    if pos:
        opp.qualification.problem = (pos.response_text or "").strip()
    # Only confirmed research crosses over as fact. Inferences travel as
    # explicitly labelled assessment; unknowns become open items to establish.
    opp.qualification.confirmed_facts = [
        f"{e.statement} (source: {e.source})" for e in t.confirmed()]
    if t.inferences():
        opp.qualification.assessment = (
            "Carried from outbound research as inference, not fact:\n"
            + "\n".join(f"- {e.statement}" for e in t.inferences()))
    opp.qualification.open_items = (
        [e.statement for e in t.unknowns()] + list(t.fit.unknowns))
    opp.qualification.fit.high_fit_signals = [s.signal for s in t.signals if s.kind == "high_fit"]
    opp.qualification.fit.problem_signals = [s.signal for s in t.signals if s.kind == "problem"]
    opp.qualification.fit.disqualifying_signals = [s.signal for s in t.signals
                                                   if s.kind == "disqualifying"]
    opp.qualification.fit.reasoning = t.fit.reasoning
    opp.log("created", f"converted from growth target {t.slug}", a.actor)
    for x in t.touches:
        if x.sent_on:
            opp.log("outreach", f"touch #{x.seq} via {x.channel} on {x.sent_on}"
                                f" — {x.response_kind or 'no response'}", a.actor)
    opp.set_status(m.PROSPECT, a.actor, f"converted from target {t.slug}")

    from .cli import _save_and_render
    written = _save_and_render(root, opp)
    t.converted_to = slug
    t.converted_on = m.today()
    t.set_status(gr.CONVERTED, a.actor, f"became clients/{slug}")
    _save(root, t)

    ok(f"{a.slug} → {c('clients/' + slug, C.ACC)}")
    dim(f"  Carried without re-entry: {len(opp.qualification.confirmed_facts)} confirmed facts, "
        f"{len(t.inferences())} inference(s) as labelled assessment, "
        f"{len(opp.qualification.open_items)} open item(s), "
        f"{len(opp.contacts)} contact(s), {len(t.sent_touches())} outreach record(s)")
    print(f"    rendered: {', '.join(sorted(written))}")
    print(f"\n{c('Next:', C.B)} mg status {slug}")
    return 0


def cmd_list(root, a):
    targets, broken = store.load_all_targets(root)
    if broken:
        err(f"{len(broken)} target(s) unreadable: " + ", ".join(s for s, _ in broken))
    if not targets:
        warn("No targets. `mg target add --company '...'` to identify one.")
        return 0
    total = len(targets)
    if not a.all:
        live = [t for t in targets if t.status not in gr.TARGET_TERMINAL]
        hidden = total - len(live)
        if live:
            targets = live
        else:
            hidden = 0
    else:
        hidden = 0
    head(f"{len(targets)} target(s)"
         + (c(f"   ({hidden} closed — --all to include)", C.D) if hidden else ""))
    w = max(len(t.slug) for t in targets)
    for t in sorted(targets, key=lambda x: (gr.TARGET_STATUSES.index(x.status), x.slug)):
        band = t.fit.band or "—"
        print(f"  {t.slug:<{w}}  {c(t.status, C.ACC):<20} {band:<12} "
              f"{c((t.company.name or '')[:26], C.D)}")
    return 0


def cmd_show(root, a):
    t = store.load_target(root, a.slug)
    head(f"{t.company.name or t.slug}  ({t.slug})")
    print(f"  Status      {c(t.status, C.ACC)}")
    print(f"  Found via   {t.identified_via or '—'}"
          + (f"   campaign {t.campaign}" if t.campaign else ""))
    print(f"  Fit         {t.fit.band or '—'}   action: {t.fit.recommended_action or '—'}")
    print(f"  Evidence    {len(t.confirmed())} confirmed · {len(t.inferences())} inferred "
          f"· {len(t.unknowns())} unknown")
    print(f"  Signals     {len(t.signals)}"
          + (c(f"   {len(t.disqualifying())} disqualifying", C.ERR) if t.disqualifying() else ""))
    head("Outreach")
    if not t.touches:
        print("  none")
    for x in t.touches:
        print(f"  #{x.seq} {x.status:<10} {x.channel or '—':<12} "
              f"sent {x.sent_on or '—':<12} response {x.response_kind or '—'}")
    head("Next")
    print(f"  {_next(t)}")
    return 0
