"""Render the SOP-required markdown artifacts from the structured record.

Every document here is generated. Nothing is retyped, so the proposal, the
project brief and the discovery notes cannot drift from each other or from the
record — which is what made "what was sold" unreconcilable before.
"""
from __future__ import annotations

from pathlib import Path

from . import model as m
from .governance import is_open


def _b(items, empty="*None recorded.*", bullet="-"):
    if not items:
        return empty
    return "\n".join(f"{bullet} {i}" for i in items)


def _yn(v):
    return {True: "Yes", False: "No", None: "*Not established*"}[v]


def _stamp(sop: str) -> str:
    return (
        f"<!-- Generated by tools/mg from opportunity.json. Do not edit by hand:\n"
        f"     edits are overwritten on the next render. Change the record instead.\n"
        f"     Procedure: {sop} -->\n"
    )


# --------------------------------------------------------------------------

def readme(opp: m.Opportunity) -> str:
    c = opp.company
    dm = opp.decision_maker
    pc = opp.primary_contact()
    be = opp.buyer_evidence
    nxt = opp.next_follow_up()
    contacts = "\n".join(
        f"| {x.name or '—'} | {x.role or '—'} | {'decision-maker' if x.is_decision_maker else ''} |"
        for x in opp.contacts
    ) or "| — | — | |"
    return f"""{_stamp('clients/README.md')}# {c.name or opp.slug}

**Client:** {c.name}
**Engagement:** {opp.solution.stage or opp.qualification.fit.stage or '*not yet located*'}
**Stage:** {opp.solution.stage or opp.qualification.fit.stage or '—'} (`SERVICES.md` §2)
**Status:** {opp.status}
**Source:** {opp.qualification.source or '*not recorded*'}
**First contact:** {opp.created_on}
**Owner:** Founder
**Last updated:** {m.today()}

---

## Quick Reference

| | |
|---|---|
| **Accountable decision-maker** | {dm.name if dm else '*not established*'} |
| **Primary contact** | {pc.name if pc else '—'} |
| **Website** | {c.website or '—'} |
| **Industry** | {c.industry or '—'} |
| **Approximate size** | {c.approximate_size or '—'} |
| **Agreement reference** | {'recorded' if opp.project.initialized_on else '—'} |

| Contact | Role | |
|---|---|---|
{contacts}

## Current Status

**{opp.status}** — set by `{m.ASSIGNED_BY.get(opp.status, '—')}`.

**Next action:** {f'{nxt.action} — {nxt.owner}, due {nxt.due}' if nxt else '*none scheduled*'}

## Buyer Evidence

*Recorded per `ICP.md` §7 to resolve Q-003. Do not generalize into `ICP.md`
directly — propose it under `governance/CHANGE_MANAGEMENT.md` once a pattern is
stable across engagements.*

| | |
|---|---|
| **Who initiated contact** | {be.initiated_contact or '—'} |
| **Who held budget** | {be.held_budget or '—'} |
| **Who could say no** | {be.could_say_no or '—'} |
| **Who had to be convinced** | {be.had_to_be_convinced or '—'} |
| **Industry / sector** | {be.industry or c.industry or '—'} |
| **Approximate size** | {be.approximate_size or c.approximate_size or '—'} |

## Rules

- **Never record a credential value here** (`MASTER.md` §7.3).
- **Never reference another client** (`MASTER.md` §7.1).
- Company documents are read-only from here — raise a change proposal
  (`governance/CHANGE_MANAGEMENT.md` §4).
"""


def qualification(opp: m.Opportunity) -> str:
    q = opp.qualification
    f = q.fit
    return f"""{_stamp('sops/sales/QUALIFICATION.md')}# QUALIFICATION — {opp.company.name or opp.slug}

**Outcome:** {q.outcome or '*pending*'}
**Decided by:** {q.decided_by or '—'} · **On:** {q.decided_on or '—'}
**Source:** {q.source or '*not recorded*'} *(evidence for Q-008)*

---

## 1. Problem and Desired Outcome

**Problem, in their words:**
{q.problem or '*not captured — qualification cannot conclude without it*'}

**Desired outcome:**
{q.desired_outcome or '*not captured*'}

## 2. Authority

Decision-maker and budget owner established: **{_yn(q.authority_confirmed)}**

{('Decision-maker: ' + opp.decision_maker.name) if opp.decision_maker else
 '*No accountable decision-maker recorded. `ICP.md` §6 treats this as a disqualification signal.*'}

## 3. Confirmed Facts

*Directly supported by the enquiry, the record, or public information.*

{_b(q.confirmed_facts)}

## 4. Assessment

*Reasoned interpretation. **Not** fact — an assessment that hardens into a fact
is how a qualification decision gets made on something nobody established
(`MASTER.md` §8.2).*

{q.assessment or q.fit.reasoning or '*No assessment recorded.*'}

{('**Recommended (agent, not decided):** ' + q.recommended_outcome) if q.recommended_outcome else ''}
{('**Recommended next action:** ' + q.recommended_next_action) if q.recommended_next_action else ''}

## 5. ICP Fit

*Assessed against `ICP.md` §4–§6. Numeric size bands are not used — they are
open (`ASSUMPTIONS.md` A-005).*

**High-fit characteristics present:**
{_b(f.high_fit_signals)}

**Problem signals present:**
{_b(f.problem_signals)}

**Disqualification signals present:**
{_b(f.disqualifying_signals, '*None identified.*')}

## 6. Delivery Feasibility

Can the company deliver this responsibly with current capacity and capability:
**{_yn(f.feasible)}**

## 7. Commercial Progression

Located in: **{f.stage or '*not located*'}** (`SERVICES.md` §2)

## 8. Outcome and Reasoning

**{q.outcome or 'Pending'}**

{q.outcome_reasoning or '*No reasoning recorded.*'}

{('### Missing information requiring resolution' + chr(10) + _b(q.open_items)) if q.open_items else ''}

---

*No price, timeline or deliverable was quoted during qualification
(`SALES.md` §6 — pricing is open, Q-007).*
"""


def discovery(opp: m.Opportunity) -> str:
    d = opp.discovery
    confirmed = [f for f in d.findings if f.confirmed]
    inferred = [f for f in d.findings if not f.confirmed]
    fmt = lambda fs: "\n".join(
        f"| `{f.ref}` | {f.topic} | {f.statement} | {f.source or '—'} |" for f in fs
    ) or "| — | — | *none* | — |"
    si = "\n".join(
        f"| {s.get('indicator','—')} | {s.get('data_source') or '**no data source — cannot be reported against**'} |"
        for s in d.success_indicators
    ) or "| — | — |"
    sh = "\n".join(
        f"| {s.get('name','—')} | {s.get('role','—')} | {s.get('influence','—')} |"
        for s in d.stakeholders
    ) or "| — | — | — |"
    return f"""{_stamp('sops/sales/DISCOVERY.md')}# DISCOVERY — {opp.company.name or opp.slug}

**Held:** {d.held_on or '*not yet held*'}
**Attendees:** {', '.join(d.attendees) or '—'}
**Playback confirmed by client:** {'Yes, ' + d.playback_on if d.playback_confirmed else '**No — mandatory before solution design** (`DISCOVERY.md` §5.9)'}

---

## 1. Confirmed Findings

*Stated by the client. These are facts for the purposes of solution design.*

| Ref | Topic | Finding | Source |
|---|---|---|---|
{fmt(confirmed)}

## 2. Inferences and Assumptions

*Not stated by the client. **Never presented to the client as their need**
(`MASTER.md` §8.2). A requirement sourced here is typed `Assumed`.*

| Ref | Topic | Inference | Basis |
|---|---|---|---|
{fmt(inferred)}

## 3. Business Objectives
{_b(d.objectives)}

## 4. Problems
{_b(d.problems)}

## 5. Constraints
{_b(d.constraints)}

## 6. Risks
{_b(d.risks)}

## 7. Opportunities
{_b(d.opportunities)}

## 8. Unknowns — answers required before proposal
{_b(d.unknowns, '*None outstanding.*')}

## 9. Success Indicators

| Indicator | Data source |
|---|---|
{si}

## 10. Stakeholders

| Name | Role | Influence |
|---|---|---|
{sh}

---

*No solution was promised and no price discussed (`DISCOVERY.md` §7).*
"""


def solution(opp: m.Opportunity) -> str:
    s = opp.solution
    rows = "\n".join(
        f"| `{r.ref}` | {r.statement} | {r.source} | {r.kind} | {r.capability or '—'} |"
        for r in opp.in_scope()
    ) or "| — | *no requirements* | — | — | — |"
    deferred = "\n".join(
        f"| `{r.ref}` | {r.statement} | {r.deferred_reason or '—'} |"
        for r in opp.deferred()
    ) or "| — | *none* | — |"
    return f"""{_stamp('sops/sales/SOLUTION_DESIGN.md')}# SOLUTION DESIGN — {opp.company.name or opp.slug}

**Approved by:** {s.approved_by or '**not approved — founder-led architecture (D-010)**'}
**On:** {s.approved_on or '—'}

---

## 1. Problem Restatement

{s.problem_restatement or '*Not restated. If it cannot be stated in one sentence, discovery is incomplete.*'}

## 2. Requirement Traceability Matrix

*Every requirement traces to a discovery finding, an explicit client statement,
or a documented assumption. **A requirement with no source is removed, not
justified** (`SOLUTION_DESIGN.md` §5.2).*

| Requirement | Statement | Source | Type | Capability |
|---|---|---|---|---|
{rows}

## 3. Minimum Viable Scope

The {len(opp.in_scope())} requirement(s) above are the smallest set that
responsibly solves the stated problem. Everything else is deferred.

## 4. Deferred

*Considered and deliberately excluded. Feeds proposal exclusions and the
expansion review at closure (`sops/delivery/CLOSURE.md` §5.11). An item deferred
because no approved capability delivers it is not an expansion candidate — it is
work the company does not do (`SERVICES.md` §3).*

| Requirement | Statement | Reason deferred |
|---|---|---|
{deferred}

## 5. Feasibility

{s.feasibility or '*Not assessed.*'}

## 6. Open Dependencies

*Requirements that cannot be specified because a company decision is open.
Never filled with a default.*

{_b(s.open_dependencies, '*None.*')}

## 7. Verification Against Discovery

Confirmed that nothing contradicts what the client said and no stated problem
is left unaddressed: **{_yn(s.verified_against_discovery)}**

## 8. Engagement Stage

**{s.stage or '*not located*'}** (`SERVICES.md` §2)
"""


def proposal_record(opp: m.Opportunity, root: Path) -> str:
    p = opp.proposal
    revs = "\n".join(
        f"| {r.get('version')} | {r.get('date')} | {r.get('changed','—')} | {r.get('why','—')} |"
        for r in p.revisions
    ) or "| — | — | *not yet issued* | — |"
    scope = _b([f"`{r.ref}` — {r.statement}" for r in opp.in_scope()])
    excl = _b([f"{r.statement} — *{r.deferred_reason or 'deferred'}*" for r in opp.deferred()],
              "*None recorded.*")
    assumed = _b([f"`{r.ref}` — {r.statement} *(assumption — client must confirm)*"
                  for r in opp.in_scope() if r.kind == "Assumed"], "*None.*")
    return f"""{_stamp('sops/sales/PROPOSAL.md')}# PROPOSAL RECORD — {opp.company.name or opp.slug}

**Status:** {p.outcome or ('Issued' if p.issued_on else 'Draft')}
**Version issued:** {p.version or '—'} · **Issue date:** {p.issued_on or '—'}
**Founder approval:** {p.approved_by or '**not approved — issuance is founder-only**'}
**Valid until:** {p.valid_until or '—'}

---

## 1. Issuance Gate

*`sops/sales/PROPOSAL.md` §5.1. `SERVICES.md` §4 requires a pricing model and
defined deliverables before an offer is presented commercially.*

| Check | Status |
|---|---|
| Commercial terms decided and recorded by the founder | {'Yes' if p.gate_terms_decided else '**No — Q-007 open**'} |
| Deliverables defined for this engagement | {'Yes' if p.gate_deliverables_defined else '**No — Q-011 open**'} |
| Gate passed — cleared to issue | {'Yes' if (p.gate_terms_decided and p.gate_deliverables_defined) else '**No**'} |

{p.gate_notes and ('**Gate notes:** ' + p.gate_notes) or ''}

## 2. Scope as Issued

*Carried unchanged from `SOLUTION.md` §3. Nothing added here.*

{scope}

## 3. Exclusions as Issued

{excl}

## 4. Assumptions the Client Must Confirm

{assumed}

## 5. Commercial Terms as Stated

{p.commercial_terms}

{'*Pricing is registered open (Q-007). "To be determined" is the only permitted value until the founder decides.*' if is_open(root, 'Q-007') else ''}

## 6. Revision History

| Version | Date | What changed | Why |
|---|---|---|---|
{revs}

## 7. Outcome

**Outcome:** {p.outcome or '*pending*'} · **Date:** {p.outcome_on or '—'}

### Reasoning
{p.outcome_reasoning or '*Not recorded.*'}

### Loss reasoning
{p.loss_reason or '*n/a*'}

*Evidence for Q-001 and Q-003 (`ICP.md` §7). A loss recorded only as "lost"
teaches the company nothing.*
"""


def project_brief(opp: m.Opportunity) -> str:
    pr = opp.project
    d, s = opp.discovery, opp.solution
    reqs = "\n".join(f"- `{r.ref}` {r.statement} *({r.kind.lower()})*" for r in opp.in_scope())
    out = "\n".join(f"- {r.statement}" for r in opp.deferred()) or "- *None recorded.*"
    ac = "\n".join(f"{i}. {c}" for i, c in enumerate(pr.acceptance_criteria, 1)) or "*Not defined — a project without acceptance criteria cannot reach acceptance.*"
    ap = "\n".join(f"| {a.get('phase','—')} | {a.get('approver','—')} |" for a in pr.approvers) or "| — | — |"
    acc = "\n".join(f"| {a.get('what','—')} | {a.get('where','—')} |" for a in pr.access_items) or "| — | — |"
    si = "\n".join(f"- {x.get('indicator')} — source: {x.get('data_source') or '*none*'}"
                   for x in d.success_indicators) or "- *None.*"
    return f"""{_stamp('sops/delivery/ONBOARDING.md')}# PROJECT BRIEF — {opp.company.name or opp.slug}

**Status:** {opp.status}
**Initialized:** {pr.initialized_on or '—'} · **Kickoff:** {pr.kickoff_on or '—'}
**Owner:** Founder
**Stage:** {s.stage or '—'} (`SERVICES.md` §2)

*Carried forward from qualification, discovery and solution design — not
re-entered. Source of every field: `opportunity.json`.*

---

## 1. Business Context
{opp.company.name} — {opp.company.industry or 'industry not recorded'}, {opp.company.approximate_size or 'size not recorded'}.
{opp.company.website}

## 2. Objective
{_b(d.objectives)}

## 3. Problem
{s.problem_restatement or opp.qualification.problem or '*not recorded*'}

## 4. Stakeholders

| Name | Role | Influence |
|---|---|---|
""" + ("\n".join(f"| {x.get('name','—')} | {x.get('role','—')} | {x.get('influence','—')} |"
                 for x in d.stakeholders) or "| — | — | — |") + f"""

## 5. Scope

### In scope
{reqs or '- *None.*'}

### Explicitly out of scope
{out}

## 6. Constraints
{_b(d.constraints)}

## 7. Dependencies — client-side
{_b(pr.client_dependencies)}

*Most timeline failures originate in client content and approval delays
(`ONBOARDING.md` §5.7).*

## 8. Assumptions

*Carried across from discovery and solution design rather than dropped — they
are the most common source of later scope disputes (`ONBOARDING.md` §5.2).*

{_b(d.assumptions + [f'{r.ref}: {r.statement}' for r in opp.in_scope() if r.kind == 'Assumed'])}

## 9. Risks
{_b(d.risks)}

## 10. Success Criteria
{si}

## 11. Acceptance Criteria

*The criteria that will end the engagement, confirmed before work starts.*

{ac}

## 12. Approvals

| Phase | Approver |
|---|---|
{ap}

## 13. Access Record

*What access exists and where credentials are stored — **never the values**
(`MASTER.md` §7.3).*

| What | Where stored |
|---|---|
{acc}

## 14. Change Log

*Material changes follow `sops/delivery/SCOPE_CHANGE.md`. The scope baseline is
`PROPOSAL.md` §2 as issued.*
"""


def proposal_document(opp: m.Opportunity, root: Path) -> str:
    """The client-facing draft. Marked DRAFT until the founder issues it."""
    p = opp.proposal
    s = opp.solution
    d = opp.discovery
    scope = "\n".join(f"- {r.statement}" for r in opp.in_scope()) or "- *None.*"
    excl = "\n".join(f"- {r.statement}" for r in opp.deferred()) or "- *None.*"
    assumed = "\n".join(f"- {r.statement}" for r in opp.in_scope() if r.kind == "Assumed") or "- *None.*"
    banner = ("> **DRAFT — FOR FOUNDER REVIEW.** Not to be sent. Agents draft; only the\n"
              "> founder approves and issues (`governance/AUTHORITY.md` §7).\n")
    if p.issued_on:
        banner = f"> Issued {p.issued_on} · version {p.version} · approved by {p.approved_by}\n"
    return f"""{_stamp('sops/sales/PROPOSAL.md')}# PROPOSAL — {opp.company.name or opp.slug}

{banner}
**Prepared by:** The Milbourne Group
**Date:** {p.issued_on or m.today()}
**Valid until:** {p.valid_until or '—'}

---

## 1. Context

{opp.company.name} — {opp.company.industry or ''} {opp.company.approximate_size or ''}

{_b(d.objectives, '')}

## 2. Problem

{s.problem_restatement or opp.qualification.problem}

## 3. Desired Outcome

{opp.qualification.desired_outcome or '*not recorded*'}

## 4. Recommended Approach

A {s.stage or 'n'} engagement (`SERVICES.md` §2), scoped to the minimum that
responsibly solves the problem above.

{s.feasibility}

## 5. Scope

{scope}

## 6. Deliverables

{'*Package deliverables are not yet defined (Q-011). The scope above states what is included; formal deliverable definitions are to be determined.*' if is_open(root, 'Q-011') and not p.gate_deliverables_defined else scope}

## 7. Exclusions

{excl}

## 8. Assumptions

*These are our assumptions, not statements of your requirements. Please confirm
or correct them.*

{assumed}

## 9. Timeline

{'To be determined.' if not p.gate_terms_decided else '*As agreed with the founder.*'}

## 10. Client Responsibilities

{_b(opp.project.client_dependencies, '- To be confirmed at onboarding.')}

## 11. Investment

{p.commercial_terms}

## 12. Acceptance and Change Process

Work is accepted against the criteria agreed at onboarding. Material changes to
objectives, deliverables or integrations follow a written change order before
implementation.

## 13. Next Step

{(opp.next_follow_up().action if opp.next_follow_up() else 'Confirm the assumptions in §8 and we will proceed to agreement.')}
"""


ARTIFACTS = {
    "README.md": (readme, None),
    "QUALIFICATION.md": (qualification, None),
    "DISCOVERY.md": (discovery, None),
    "SOLUTION.md": (solution, None),
    "PROPOSAL.md": (proposal_record, "root"),
    "PROPOSAL_DRAFT.md": (proposal_document, "root"),
    "PROJECT_BRIEF.md": (project_brief, None),
}


def render_all(opp: m.Opportunity, root: Path) -> dict[str, str]:
    """Render the artifacts that the opportunity has actually reached."""
    out: dict[str, str] = {"README.md": readme(opp)}
    if opp.qualification.outcome or opp.qualification.problem:
        out["QUALIFICATION.md"] = qualification(opp)
    if opp.discovery.held_on or opp.discovery.findings:
        out["DISCOVERY.md"] = discovery(opp)
    if opp.solution.requirements:
        out["SOLUTION.md"] = solution(opp)
    if opp.proposal.version or opp.proposal.gate_notes or opp.proposal.outcome:
        out["PROPOSAL.md"] = proposal_record(opp, root)
        out["PROPOSAL_DRAFT.md"] = proposal_document(opp, root)
    if opp.project.initialized_on:
        out["PROJECT_BRIEF.md"] = project_brief(opp)
    return out
